Rookie.CustomerSite/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.Shared.Dto.Review;
using RookieShop.Shared.Request.Review;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rookie.CustomerSite.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewService _reviewService;
        public ReviewController(IReviewService reviewService)
        {
            _reviewService = reviewService;
        }

        public async Task<IActionResult> ProductReview([Bind("Stars, Content, ProductId")] ReviewCreateRequest review)
        {
            if (ModelState.IsValid)
            {
                await _reviewService.PostReview(review);
                return Redirect($"../ProductDetail?id={review.ProductId}");
            }
            else
                return Redirect($"../ProductDetail?id={review.ProductId}");
        }

    }
}

Rookie.CustomerSite/Areas/ProductDetail/Pages/Shared/_StarReviewPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="review-form">
    <h3><strong>Your Review</strong></h3>
    <form id="rating" method="post" asp-controller="Review" asp-action="ProductReview">
        <div class="star-review">
            <i id="Stars" name="Stars" class="fa fa-star star" data-value="1"></i>
            <i id="Stars" name="Stars" class="fa fa-star star" data-value="2"></i>
            <i id="Stars" name="Stars" class="fa fa-star star" data-value="3"></i>
            <i id="Stars" name="Stars" class="fa fa-star star" data-value="4"></i>
            <i id="Stars" name="Stars" class="fa fa-star star" data-value="5"></i>
        </div>
        <textarea id="Content" name="Content" placeholder="Please enter your review"></textarea>
        <input id="ProductId" name="ProductId" class="disabled" type="hidden" value="@ViewBag.ProductId" />
        <div class="right">
            <button class="btn btn-success" type="submit">Save</button>
            <button class="btn btn-danger" type="reset">Cancel</button>
        </div>
    </form>
</div>