Rookie.CustomerSite/Areas/Home/Pages/Index.cshtml.cs
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Rookie.CustomerSite.ViewModel;
using Rookie.CustomerSite.ViewModel.Banner;
using Rookie.CustomerSite.ViewModel.Product;
using RookieShop.Shared.Constants;
using RookieShop.Shared.Dto.Banner;
using RookieShop.Shared.Dto.Product;
using RookieShop.Shared.Enum;

namespace Rookie.CustomerSite.Pages.Home
{
    public class IndexModel : PageModel
    {
        private readonly IBannerService _bannerService;
        private readonly IConfiguration _config;
        private readonly IMapper _mapper;

        public IndexModel(
            IBannerService bannerService,
            IProductService productService,
            IConfiguration config,
            IMapper mapper)
        {
            _bannerService = bannerService;
            _config = config;
            _mapper = mapper;
        }

        public PagedResponseVM<BannerVm> Banners { get; set; }

        public async Task OnGetAsync()
        {
            var bannerCriteriaDto = new BannerCriteriaDto()
            {
                SortOrder = SortOrderEnum.Accsending,
                Limit = int.Parse(_config[ConfigurationConstants.PAGING_LIMIT])
            };
            var pagedbanners = await _bannerService.GetBannerAsync(bannerCriteriaDto);
            Banners = _mapper.Map<PagedResponseVM<BannerVm>>(pagedbanners);
        }
    }
}

Rookie.CustomerSite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rookie.CustomerSite.Models;
using RookieShop.Shared.Dto.Brand;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Rookie.CustomerSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBrandService _brandService;

        public HomeController(
            ILogger<HomeController> logger,
            IBrandService brandService
            )
        {
            _logger = logger;
            _brandService = brandService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rookie.CustomerSite/ViewComponents/NewArrivalViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Rookie.CustomerSite.ViewModel;
using Rookie.CustomerSite.ViewModel.Product;
using RookieShop.Shared.Constants;
using RookieShop.Shared.Dto.Product;
using RookieShop.Shared.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rookie.CustomerSite.ViewComponents
{
    public class NewArrivalViewComponent : ViewComponent
    {
        private readonly IProductService _productService;
        private readonly IConfiguration _config;
        private readonly IMapper _mapper;

        public NewArrivalViewComponent(
            IProductService productService,
            IConfiguration config,
            IMapper mapper
            )
        {
            _productService = productService;
            _config = config;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync ()
        {
            var productCriteriaDto = new ProductCriteriaDto()
            {
                SortOrder = SortOrderEnum.Accsending,
                Limit = int.Parse(_config[ConfigurationConstants.PAGING_LIMIT])
            };
            var pagedProducts = await _productService.GetProductAsync(productCriteriaDto);
            var products = _mapper.Map<PagedResponseVM<ProductVm>>(pagedProducts);

            return View(products);
        }
    }
}

Rookie.CustomerSite/Areas/Home/Pages/Index.cshtml
@page
@model Rookie.CustomerSite.Pages.Home.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "RookieShop";
    Layout = "_Layout";
}
<div class="container">
    <!-- /#banner-slider-->
    <div id="banner" class="owl-carousel owl-theme">
        @foreach (var item in Model.Banners.Items)
        {
            <div class="item">
                <img src="@item.ImagePath">
            </div>
        }
    </div>
</div>
<!--
*** ADVANTAGES HOMEPAGE ***
_________________________________________________________
-->
<partial name="_AdvantagesPartial" />
<!-- *** ADVANTAGES END ***-->

<!--
*** HOT PRODUCT SLIDESHOW ***
_________________________________________________________
-->
@await Component.InvokeAsync("NewArrival") 
<!-- /#hotproduct-->

@section ajax{
    <script>
        $(function () {
            $(document).ready(function () {
                $("#banner").owlCarousel({
                    autoplay: true,
                    navigation: true,
                    loop: true,
                    items: 1,
                    autoHeight: true,
                });
                $("#hot .owl-carousel").owlCarousel({
                    center: true,
                    loop: true,
                    autoplay: true,
                    margin: 15,
                    items: 1,
                    autoHeight: true,
                    responsive: {
                        600: {
                            items: 2
                        },
                        900: {
                            items: 3
                        },
                        1200: {
                            items: 4
                        }
                    }
                });
            });
        });</script>
}